models/dataEntities.go
transformer/transformer.go

Add transaction date to eshu file .

Add transaction date to eshu file

---

transformer/transformer.go

Change to replace underscore with a minus sign in the order reference field.

Change to replace underscore with a minus sign

---

assets/product_code.yml
data/paymentDetailResponse.go
service/service.go
service/service_test.go
transformer/transformer.go

Change to replace secure data values with blank strings when writing data to the payment reconciliation collection

Change to replace secure data values with blank strings

---

Makefile

Clean up unused dependencies using `go mod tidy`.

 Clean up unused dependencies using go mod tidy

---

assets/product_code.yml

Add product codes for certificates

---

assets/product_code.yml

Adds product codes for Certified Copies

Add product codes for certified copies enums

---

assets/product_code.yml

**GCI-996** Update MID enumeration for the payments service

Update MID enumeration for the payments service

---

assets/product_code.yml

Jira Ticket: https://companieshouse.atlassian.net/browse/SR-55
Finance Product code:
16033 = SR01

Add product type and finance code for Suppression Application

---

assets/product_code.yml

Finance Product codes:
40101 = SLPCS01
40102 = SQPCS01
BI-5191

Add product type and finance code for 2 EFS payable submissions

---

assets/product_code.yml

Amended product codes for missing-image-deliveries items
Jira Ticket GCI-1697

Amended product codes for missing-image-deliveries items

---

assets/product_code.yml

Finance Product codes:
40103 = SH19
BI-5544

Add SH19 product code from EFS

---

assets/product_code.yml

Add the product code for SH19 same day coming from the EFS service
BI-7847

Add the product code for SH19 same day

---

go.sum
service/service.go

New refund request can now have the status `refund-requested`, so check for that status here.
Also ran `go mod tidy`
ROE-1681

Add status check for refund-requested

---

assets/product_code.yml

JIRA https://companieshouse.atlassian.net/browse/UAR-890
Add product code for update-overseas-entity. Product code as supplied by Finance.

uar-890 add update-overseas-entity product code

---

assets/product_code.yml

Note that digital-certificates are not included here. (product code 25141)

fix product codes for dcac products

---

assets/product_code.yml

https://companieshouse.atlassian.net/browse/UAR-871
Add product code for remove-overseas-entity. Product code as supplied by Finance.

UAR-871 New product code for ROE Remove

---

assets/product_code.yml

Resolves [BI-12026](https://companieshouse.atlassian.net/browse/BI-12026)
Add product code for CHS additional copies in payment reconciliation files
[BI-12026]: https://companieshouse.atlassian.net/browse/BI-12026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BI-12026- add new product code for chs additional copies orders

---

assets/product_code.yml

Resolves [BI-12026](https://companieshouse.atlassian.net/browse/BI-12026) 
Replace new additional product code onto existing certificate-additional copies description 
[BI-12026]: https://companieshouse.atlassian.net/browse/BI-12026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BI-12026-replace new additional product code onto existing additional copies desc

---

assets/product_code.yml

adding product code for cic package accounts.

add product code for cic package accounts

---

README.md
terraform/groups/ecs-service/data.tf
terraform/groups/ecs-service/locals.tf
terraform/groups/ecs-service/main.tf
terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars
terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
terraform/groups/ecs-service/variables.tf
terraform/groups/ecs-service/vault-providers/approle
terraform/groups/ecs-service/vault-providers/token
terraform/groups/ecs-service/vault-providers/userpass
terraform/groups/ecs-service/vault.tf
terraform/groups/ecs-service/version

```
Plan: 8 to add, 0 to change, 0 to destroy.
───────────────────────────────────────────────────────────────────────────────
Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.
```

JU-1581: Add terraform code

---

assets/product_code.yml

https://companieshouse.atlassian.net/browse/LP-752
Add product code for register-limited-partnership

LP-752 Add register-limited-partnership product code

---

terraform/groups/ecs-service/locals.tf
terraform/groups/ecs-service/main.tf

This pr will add another version of same service but with config setup for latest kafka cluster resolves https://companieshouse.atlassian.net/browse/CC-2750

Kafka Upgrade Changes
